### PR TITLE
DBZ-5808 deserialize BigInteger values from the Cassandra driver

### PR DESCRIPTION
**Pull request by keriharris**
https://issues.redhat.com/browse/DBZ-5808

### CODE REVIEW

**Comment by jpechane** [comment]
@keriharris Thanks for the PR! Could you please send another one to core repo with docs update? Thanks a lot.

**Comment by jpechane** [comment]
@keriharris Thanks for the PR. Unfortunately this would break the backward compatibility. Could you please extend the implementation in the same way we provide in other connectors? See https://debezium.io/documentation/reference/2.0/connectors/mysql.html#mysql-property-bigint-unsigned-handling-mode

It is the same issue as the other PR. Also it would reuqire a specific documentation format like in https://debezium.io/documentation/reference/2.0/connectors/mysql.html#mysql-decimal-types

In both cases the default values will reflect current behaviour. This means that there would be no issue with migration yet it would be possible to switch according to the user needs. We could change the default later and properly document.

**Comment by keriharris** [comment]
Thanks for the comments; they were helpful in guiding me in the right direction.

I've pushed another commit that maintains backwards compatibility. It introduces a `varint.handling.mode` Cassandra config setting that respects the following values:
* long. This is the default which deserializes varint columns to Java.long.
* precise. This deserializes varint columns to `org.apache.kafka.connect.data.Decimal` type.
* string. This deserializes to formatted strings.

With this change I get:

```
CREATE TABLE IF NOT EXISTS mykeyspace.test ( k text, v varint, PRIMARY KEY (k) ) WITH cdc=true;
INSERT INTO mykeyspace.test ( k, v ) VALUES ( 'a', 100 );
```

* default (or by explicitly setting `varint.handling.mode=long`)

`"v":{"value":100,"deletion_ts":null,"set":true}`

full change event:
```json
{"schema":{"type":"struct","fields":[{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":false,"field":"op"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"cluster"},{"type":"string","optional":false,"field":"file"},{"type":"int32","optional":false,"field":"pos"},{"type":"string","optional":false,"field":"keyspace"},{"type":"string","optional":false,"field":"table"}],"optional":false,"name":"source","field":"source"},{"type":"struct","fields":[{"type":"struct","fields":[{"type":"string","optional":true,"field":"value"},{"type":"int64","optional":true,"field":"deletion_ts"},{"type":"boolean","optional":false,"field":"set"}],"optional":true,"name":"k","field":"k"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"value"},{"type":"int64","optional":true,"field":"deletion_ts"},{"type":"boolean","optional":false,"field":"set"}],"optional":true,"name":"v","field":"v"},{"type":"string","optional":true,"field":".range_start"},{"type":"string","optional":true,"field":".range_end"}],"optional":false,"name":"after","field":"after"}],"optional":false,"name":"io.debezium.connector.cassandra.debezium.json.mykeyspace.test.Envelope"},"payload":{"ts_ms":1668081437609,"op":"i","source":{"version":"2.1.0-SNAPSHOT","connector":"cassandra","name":"debezium.json","ts_ms":1668081434766,"snapshot":"false","db":"NULL","sequence":null,"cluster":"My Cluster","file":"CommitLog-7-1668081247310.log","pos":1220437,"keyspace":"mykeyspace","table":"test"},"after":{"k":{"value":"a","deletion_ts":null,"set":true},"v":{"value":100,"deletion_ts":null,"set":true},".range_start":null,".range_end":null}}}
```

* `varint.handling.mode=precise`

`"v":{"value":"ZA==","deletion_ts":null,"set":true}`

full change event:
```json
{"schema":{"type":"struct","fields":[{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":false,"field":"op"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"cluster"},{"type":"string","optional":false,"field":"file"},{"type":"int32","optional":false,"field":"pos"},{"type":"string","optional":false,"field":"keyspace"},{"type":"string","optional":false,"field":"table"}],"optional":false,"name":"source","field":"source"},{"type":"struct","fields":[{"type":"struct","fields":[{"type":"string","optional":true,"field":"value"},{"type":"int64","optional":true,"field":"deletion_ts"},{"type":"boolean","optional":false,"field":"set"}],"optional":true,"name":"k","field":"k"},{"type":"struct","fields":[{"type":"bytes","optional":false,"name":"org.apache.kafka.connect.data.Decimal","version":1,"parameters":{"scale":"0"},"field":"value"},{"type":"int64","optional":true,"field":"deletion_ts"},{"type":"boolean","optional":false,"field":"set"}],"optional":true,"name":"v","field":"v"},{"type":"string","optional":true,"field":".range_start"},{"type":"string","optional":true,"field":".range_end"}],"optional":false,"name":"after","field":"after"}],"optional":false,"name":"io.debezium.connector.cassandra.debezium.json.mykeyspace.test.Envelope"},"payload":{"ts_ms":1668081558052,"op":"i","source":{"version":"2.1.0-SNAPSHOT","connector":"cassandra","name":"debezium.json","ts_ms":1668081543687,"snapshot":"false","db":"NULL","sequence":null,"cluster":"My Cluster","file":"CommitLog-7-1668081507828.log","pos":1220643,"keyspace":"mykeyspace","table":"test"},"after":{"k":{"value":"a","deletion_ts":null,"set":true},"v":{"value":"ZA==","deletion_ts":null,"set":true},".range_start":null,".range_end":null}}}
```

* `varint.handling.mode=string`

`"v":{"value":"100","deletion_ts":null,"set":true}`

full change event:
```json
{"schema":{"type":"struct","fields":[{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":false,"field":"op"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"cluster"},{"type":"string","optional":false,"field":"file"},{"type":"int32","optional":false,"field":"pos"},{"type":"string","optional":false,"field":"keyspace"},{"type":"string","optional":false,"field":"table"}],"optional":false,"name":"source","field":"source"},{"type":"struct","fields":[{"type":"struct","fields":[{"type":"string","optional":true,"field":"value"},{"type":"int64","optional":true,"field":"deletion_ts"},{"type":"boolean","optional":false,"field":"set"}],"optional":true,"name":"k","field":"k"},{"type":"struct","fields":[{"type":"string","optional":true,"field":"value"},{"type":"int64","optional":true,"field":"deletion_ts"},{"type":"boolean","optional":false,"field":"set"}],"optional":true,"name":"v","field":"v"},{"type":"string","optional":true,"field":".range_start"},{"type":"string","optional":true,"field":".range_end"}],"optional":false,"name":"after","field":"after"}],"optional":false,"name":"io.debezium.connector.cassandra.debezium.json.mykeyspace.test.Envelope"},"payload":{"ts_ms":1668081689348,"op":"i","source":{"version":"2.1.0-SNAPSHOT","connector":"cassandra","name":"debezium.json","ts_ms":1668081686328,"snapshot":"false","db":"NULL","sequence":null,"cluster":"My Cluster","file":"CommitLog-7-1668081659212.log","pos":33013,"keyspace":"mykeyspace","table":"test"},"after":{"k":{"value":"a","deletion_ts":null,"set":true},"v":{"value":"100","deletion_ts":null,"set":true},".range_start":null,".range_end":null}}}
```

**Comment by jpechane** [comment]
Please take a look at comments in https://github.com/debezium/debezium-connector-cassandra/pull/78
They'd be the same. Thanks!

**Comment by jpechane** [comment]
@keriharris Applied, thanks for nice job!

**Pull request merged**
