### PR TITLE
[DBZ-2974]: Fix deserialization of List<UserType> columns

### PR DESCRIPTION
**Pull request by bingqinzhou**
https://issues.redhat.com/browse/DBZ-2974

### CODE REVIEW

**Comment by bingqinzhou** [comment]
@gunnarmorling Can I get a review for this PR when you get a chance please? Thank you!

**Review by gunnarmorling — APPROVED** [review]
LGTM, but could you add a test for the affected situation, too? Thx!

**Comment by bingqinzhou** [comment]
> LGTM, but could you add a test for the affected situation, too? Thx!

Added tests for this :)

**Comment by gunnarmorling** [comment]
Excellent, thx! If I could suggest one thing, it'd be to squash the commits into one in cases like this, where there are many intermediary commits, which aren't interesting in the long term to keep separate. But no worries, we can do that next time. Thanks again!

**Comment by gunnarmorling** [comment]
Debezium 1.5.0.Alpha1 (including this fix) is scheduled for next week btw.

**Pull request merged**
