### PR TITLE
DBZ-6576

### PR DESCRIPTION
**Pull request by smiklosovic**

### CODE REVIEW

**Comment by jpechane** [comment]
@smiklosovic ok, I am removing it from 2.3 stable branch until furter feedback is provided

**Comment by ahmedjami** [comment]
Hi @smiklosovic @jpechane 
Sorry for the delay.
I have tested the fix and it looks good to me. However, our dev team want to make more tests to be sure that the change does not bring any regression. 
I will let you know as soon as I get feedback. 
Greetings,

**Comment by ahmedjami** [comment]
Hi @smiklosovic @jpechane 
The dev team has just confirmed that all tests were performed with success.
Greetings,
Ahmed

**Comment by jpechane** [comment]
@smiklosovic I am willing to backport to 2.3. Any objections?

**Comment by smiklosovic** [comment]
@jpechane I have none.

**Comment by jpechane** [comment]
@smiklosovic Done, thanks

**Pull request merged**
