### PR TITLE
DBZ-5925 Bring back fatjar

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-5925

### CODE REVIEW

**Comment by jpechane** [comment]
@smiklosovic Could you please give it a test ride so we can get the wroking standalone JAR back? Thanks

**Comment by smiklosovic** [comment]
I tried it, it works, connector starts, it connects to Kafka ...

**Comment by smiklosovic** [comment]
@jpechane yeah it works. Can you explain what this change does? I am not sure I follow.

**Comment by smiklosovic** [comment]
right ... it looks just fine, I tried to run and build it and it just ... worked.

**Pull request merged**
