### PR TITLE
DBZ-5826 fix names of range fields in schema to comply with Avro standard

### PR DESCRIPTION
**Pull request by smiklosovic**

### CODE REVIEW

**Comment by smiklosovic** [comment]
@jpechane kindly pinging

**Comment by jpechane** [comment]
@smiklosovic There is a class `io.debezium.data.VerifyRecord`. It might be useful to place few calls around the codebase to make sure that messages are valid.

**Comment by smiklosovic** [comment]
Is this still necessary to do? I pinged you in the ticket that this might go in as is.

**Comment by jpechane** [comment]
@smiklosovic Applied, thanks! The remark was a generic one as using those methods would catch such issues right at the start.

**Pull request merged**
