### PR TITLE
DBZ-7618 Prevent multiple calls to pu.maxTimestamp()

### PR DESCRIPTION
**Pull request by samssh**
Invoking the `pu.maxTimestamp()` function within the `handleRowModifications` method, which is inside a loop in `handleRowIterator`, can lead to performance issues and significantly slow down the connector.

### CODE REVIEW

**Comment by samssh** [comment]
https://issues.redhat.com/browse/DBZ-7622

**Comment by jpechane** [comment]
@samssh Applied, thanks!

**Comment by Ficooooooo** [comment]
> Invoking the `pu.maxTimestamp()` function within the `handleRowModifications` method, which is inside a loop in `handleRowIterator`, can lead to performance issues and significantly slow down the connector.

Hi @samssh,  I've encountered with performance issue as well, and I've test performance of 2.5.3.Final, it seems like there is no difference on performance when reading the commit log files, did I use the wrong version or I need to change some configurations? 

And based on your test, is the problem fixed?

**Comment by samssh** [comment]
> > Invoking the `pu.maxTimestamp()` function within the `handleRowModifications` method, which is inside a loop in `handleRowIterator`, can lead to performance issues and significantly slow down the connector.
> 
> Hi @samssh, I've encountered with performance issue as well, and I've test performance of 2.5.3.Final, it seems like there is no difference on performance when reading the commit log files, did I use the wrong version or I need to change some configurations?
> 
> And based on your test, is the problem fixed?

Hi @Ficooooooo. I answered your question [here](https://issues.redhat.com/browse/DBZ-7704?focusedId=24466621&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24466621)

**Pull request merged**
