### PR TITLE
DBZ-5925 Keep fatjar and provide slimmed plugin distro

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Review by ggaborg — COMMENTED** [review]
same changes in cassandra-3 pom need to be done to cassandra-4 pom

**Comment by jpechane** [comment]
@ggaborg of course, this is just a validation of approach, not even all dpes has been exluded yet. I am trying to find a common ground and chekcing if it is the case.

**Comment by smiklosovic** [comment]
If I understand it right, if debezium-server will contain Cassandra, will server depend - Maven-wise - on what we ship? (server will reference this connector in its dependencies? What does "out of the box mean" here?

Could not we wait until debezium-server is out so we do not need to ship plugin so this whole work would be probably just abandoned?

**Comment by jpechane** [comment]
Closing in favour of https://github.com/debezium/debezium-connector-cassandra/pull/99 and https://github.com/debezium/debezium/pull/4231

**Pull request closed without merging**
