### PR TITLE
DBZ-2870 Enforce Java 8

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-2870

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, that build failure is interesting, it reveals that this job is building to much of the main repo. It should build only _debezium-core_ and in turn what this one depends on.

**Comment by gunnarmorling** [comment]
Ha, you beat me to it, just was about to push the very same change but it got rejected :)

**Comment by jpechane** [comment]
@gunnarmorling ou know, someimes I am faster than light ;-)

**Comment by gunnarmorling** [comment]
Admit, you had shelved that change before and only waited with pushing it, so to aggravate me ;)

**Pull request merged**
