### PR TITLE
DBZ-3906 add protobuf converter

### PR DESCRIPTION
**Pull request by fuxiao224**

### CODE REVIEW

**Comment by fuxiao224** [comment]
Hi @bingqinzhou and @gunnarmorling ! Would you please take a look at this small change about adding Protobuf Converter in dependency list? Thanks!

**Comment by bingqinzhou** [comment]
LGTM. @gunnarmorling Does the change look ok to you please?

**Comment by gunnarmorling** [comment]
@bingqinzhou, I think it does. The one question is: this will add that converter JAR and all its dependencies to the Cassandra connector distribution, right? So could you compile a list with the license of all the involved JARs (the converter, dependencies and any potential transitive dependencies)? That'd help to make sure we can actually publish this. Thanks!

**Comment by bingqinzhou** [comment]
> @bingqinzhou, I think it does. The one question is: this will add that converter JAR and all its dependencies to the Cassandra connector distribution, right? So could you compile a list with the license of all the involved JARs (the converter, dependencies and any potential transitive dependencies)? That'd help to make sure we can actually publish this. Thanks!

Hi Gunnar, thank you for the comment! I don't totally understand what is needed here. Could you please explain more?

Currently we have all kafka-connect related dependencies listed in pom.xml like below:

```<!-- Kafka Connect -->
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-json</artifactId>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-connect-avro-converter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-connect-protobuf-converter</artifactId>
        </dependency>```

**Comment by fuxiao224** [comment]
Hi @gunnarmorling ! I wonder if you are looking for license information like listed in the following link?
For avro convertor: (Apache License 2.0) https://www.confluent.io/hub/confluentinc/kafka-connect-avro-converter
For Protobuf convertor: (MIT License) https://www.confluent.io/hub/blueapron/kafka-connect-protobuf-converter
Thanks! cc @bingqinzhou

**Pull request merged**
