### PR TITLE
DBZ-3262

### PR DESCRIPTION
**Pull request by JeremyVigny**
https://issues.redhat.com/browse/DBZ-3262

I tested debezium with cassandra and there is no regression:
- works without SSL
- works with SSL without adding additional properties
- works with SSL with adding additional properties (list of ciphers)

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Very nice! I think it looks good, I'll defer to @bingqinzhou and @ahmedjami for the details. In the meantime, could you please:

* Rework the commit so it doesn't have the "octocat" icon next to it (i.e. only authoring it using a single email address that's linked to your GH account)
* Send a PR for updating the connector docs (https://github.com/debezium/debezium/blob/master/documentation/modules/ROOT/pages/connectors/cassandra.adoc) to add the new attribute at least (it seems the other SSL attributes are missing there, too; purely optional, it'd be lovely if we could have added them all (I know, I'm greedy ;))

**Comment by ahmedjami** [comment]
New Jira Issue to update connector docs => https://issues.redhat.com/browse/DBZ-3312

And I had already checked the changes here with @JeremyVigny, LGTM ;)

**Comment by bingqinzhou** [comment]
LGTM, thanks.

**Comment by gunnarmorling** [comment]
> New Jira Issue to update connector docs => https://issues.redhat.com/browse/DBZ-3312

Thanks! Let's still add the docs for new option right now, so to not further increase the "docs debt".

> And I had already checked the changes here with @JeremyVigny, LGTM ;)

Excellent; so then only the commit authorship needs fixing as discussed above, and we can merge it. Thanks all!

**Comment by JeremyVigny** [comment]
Thanks for your remark @gunnarmorling . I think it's good, I cleaned up the commits

**Comment by gunnarmorling** [comment]
Excellent, applied. Thanks!

**Pull request merged**
