### PR TITLE
[DBZ-3590]: Change valueSchema name to be Envelope.

### PR DESCRIPTION
**Pull request by bingqinzhou**
Change the Kafka value of change event from Cassandra Connector to be name with `Envelope` suffix.

https://issues.redhat.com/projects/DBZ/issues/DBZ-3590

### CODE REVIEW

**Comment by bingqinzhou** [comment]
@gunnarmorling Could you please take a look at this one-line PR when you get a chance please? This is to address the issue reported in DBZ-3590. Thank you!

**Comment by gunnarmorling** [comment]
@bingqinzhou, this LGTM. Could you only also update the examples in the connector docs (_documentation/modules/ROOT/pages/connectors/cassandra.adoc_) accordingly? Thanks!

**Comment by bingqinzhou** [comment]
> @bingqinzhou, this LGTM. Could you only also update the examples in the connector docs (_documentation/modules/ROOT/pages/connectors/cassandra.adoc_ in the main repo) accordingly? Thanks!

@gunnarmorling Sure, I updated the doc in https://github.com/debezium/debezium/pull/2524

**Comment by gunnarmorling** [comment]
Applied; thx, @bingqinzhou!

**Pull request merged**
